snapshot-labs/envelop

src/templates/summary/index.ts

`proposals` params was destructured instead of nested inside a `proposals` key

fix: fix proposals params not nested correctly

---

src/helpers/snapshot.ts
src/templates/summary/index.hbs

Add an indicator if already voted for a proposal on summary
Current indicator in template is a placeholder, will need to be improved via #6

feat: add indicator if already voted for a proposal on summary

---

src/preview/index.ts

Drop query params customization from email previewer, to avoid leaking sensitive data

fix: remove query params customization

---

src/helpers/snapshot.ts
src/preview/index.ts
test/unit/helpers/snapshot.test.ts

This PR show all proposals for all the addresses related to the same email address in the same summary email.

feat: summary email for multiple addresses

---

src/templates/builder.ts

`preheader` was defined in templates/index.ts, but were never injected properly in the handlebars files

fix: fix missing preheader injection in templates

---

src/helpers/schema.sql

Fix missing default value for `verified` column in the sql schema

fix: fix missing `DEFAULT` value in schema

---

src/helpers/snapshot.ts
src/templates/summary/html.hbs
src/templates/summary/index.ts

In email summary, the total stats count for each status (active/pending/closed) was reflecting the number of spaces for each status, instead of the total number of proposals.
Show the proposals count, instead of spaces count

fix: fix wrong proposals stats

---

src/queues/index.ts

Fix issue causing 100% CPU usage when using a remote redis instance.
This issue does not arise when using a local redis instance (redis://127.0.0.1:6379), and only happens when using a remote redis (production case).
Issue was fixed by re-using redis connection when possible (https://github.com/OptimalBits/bull/blob/master/PATTERNS.md#reusing-redis-connections), and explicitly set the redis options (https://github.com/OptimalBits/bull/issues/1873#issuecomment-950873766)

fix: fix high CPU usage on production server

---

src/queues/processors/scheduler.ts

Adding a jobId will ensure this job execute only once.
Re-queuing this job with same ID will skip subsequent processing, ensuring job idempotency

feat: ensure email will be processed only once

---

src/templates/builder.ts
src/templates/utils.ts

The string padding code is not taking into account string longer than the expected max length, and results in calling `repeat()` with a negative value.
Fix #76
Avoid padding the string when it is already exceeding the string limit.
- Add a check to skip padding when the string does not need padding
Internal change only. Since we already control the length of the string in templates/index.ts, this fix is just a prevention

fix: fix issue when trying to pad a string already longer than the target length

---

src/preview/index.ts
src/preview/utils.ts

When using `/preview/summary`, we can only preview the content of the summary emails, for the address hardcoded in `constants.json`.
We should be able to customize this address, via url query params, so we can preview the summary email for different addresses, to test content and issues reported by users on specific addresses.
- Add ID query params to `/summary/preview`, to customize the wallet address associated to the summary
Go to `/preview/summary` and use another address with `?id=[ADDRESS]`. It should show the summary for the given address. It also support multiple addresses, separate them with a comma

fix: fix missing ID customization in summary preview

---

package.json
yarn.lock

Typescript is currently locked to version < 5, due to Jest lack of support. Jest was the only dependencies preventing us from upgrading to v5.
Jest now support typescript 5, since 29.1.0 (merged via https://github.com/snapshot-labs/envelop/pull/84), so we can now safely update to typescript 5
- Change the required version in `package.json`, to install typescript `^5.0.0`
Run `yarn test` and `yarn test:e2e`. They should run without any warnings about unsupported typescript 5.

chore(deps-dev): update to typescript 5

---

src/rpc.ts
src/templates/builder.ts
src/templates/partials/layout.html.hbs
src/templates/partials/layout.text.hbs
src/templates/utils.ts
test/e2e/update.test.ts
test/unit/templates/index.test.ts

The link in the email footer is labeled `Unsubscribe`, but leads to a page where user can either update the email preferences, or unsubscribe
There should be 2 different links in the email footer:
- `Manage email preferences` : leads to a page where user can update his email preferences. Even with all options unchecked, this form will just disable email sending to this email address, without removing it from the database.
- `Unsubscribe` : leads to a page which will unsubscribe the user upon loading (bringing back the original unsubscribe page/workflow). This action will remove the email and all its associated addresses from the database.
- Add a new `Manage email preferences` link in the footer
- Minor fix to API endpoint, to ignore subscriptions params when checking the signature, when …

feat: separate update and unsubscribe link in footer

---

src/rpc.ts

Header keyname for checking the webhook authentication key is incorrect
Change the header keyname to the correct one
- Rename key from `authenticate` to `Authentication`
- Nothing

fix: fix incorrect webhook auth header name

---

src/rpc.ts

Webhook authentication detection is failing.
Fix header detection to use the correct name, `fetch` auto downcase all header name.
Mirror PR of https://github.com/snapshot-labs/snapshot-sidekick/pull/64 by @ChaituVR 
- Use 'authencation' instead of `Authentication`, for the header key name
- Add some other fixes to prevent errors when webhook body is empty
- Nothing

fix: fix webhook auth header detection

---

src/helpers/utils.ts
src/rpc.ts
test/e2e/subscriber.test.ts
test/unit/helpers/utils.test.ts

Current subscriptions status are `subscribed` and `not subscribed`, and there is no status for email pending verification. 
Fix #63
Add a new `UNVERIFIED` status, when pending for an address subscriptions.
**BREAKING CHANGES**
- Update the `subscriber` endpoint, to return a subscriber object, instead of just an array of subscriptions
New returned response will look like: 
```
{
state: 'VERIFIED',
email: 'wa****@email.com',
subscriptions: ['summary']
}
```
When email is verified, return state `VERIFIED`
When email is pending verification, return state `UNVERIFIED`
When email does not exist, return HTTP 404 status code
`email` field will be obfuscated, and will show only the first 2 characters before `@`
- Send a POST request to `subscriber`: ` curl -X POST localhost:3006/subscriber -H …

feat: return subscriber state

---

scripts/send-subscribe.ts
src/queues/index.ts
src/rpc.ts
src/templates/subscribe/index.ts
test/e2e/verify.test.ts

Email verification link is missing the `salt` params, making all verification link fail
Fix #126 
Add the missing `salt` params to verification link
- Inject the missing `salt` link to all verification links
- Go to `/preview/verify`. The verify link should contains the `salt` param
- You can also test sending yourself an email with the `send-subscribe` scripts. 
If you want to test the whole workflow with envelop-ui, test with the PR https://github.com/snapshot-labs/envelop-ui/pull/17

fix: fix missing `salt` in email verification link

---

.github/workflows/build-test.yml

Redis instance is missing on CI
Install redis instance on CI
- Add redis service to github workflow
- Nothing to do

chore: fix missing redis instance on CI

---

src/templates/closedProposal/html.hbs
src/templates/newProposal/html.hbs
src/templates/partials/layout.html.hbs
src/templates/partials/proposals.html.hbs
src/templates/subscribe/html.hbs
src/templates/summary/html.hbs

New and Closed proposal emails are not taking the full width when there is not enough content
Fix the issues
- Add a width="100%" to all table element
- Visit `http://localhost:3006/preview/newProposal?id=0x6fcbd2e1af981e9c19baa62d83183e521caeb361ca7f96441552ddcb38188d61`. The email content should take the full width

fix(UI): fix content not taking up the full width

---

src/helpers/utils.ts
test/unit/helpers/utils.test.ts

Email address with special characters are not obfuscating
Fix #128 
- Fix the regex to take not ignore special characters
- Run `yarn test`. See `test/unit/helpers/utils.test.ts`

fix: fix email obfuscation not working with special characters

---

src/templates/closedProposal/index.ts
src/templates/newProposal/index.ts
src/templates/utils.ts

The READ MORE link in truncated proposal body is not valid, it shows `${proposal.link}` instead
Fix the link
- Fix the invalid link
- Visit `http://localhost:3006/preview/newProposal?id=0x6b703b90d3cd1f82f7c176fc2e566a2bb79e8eb6618a568b52a4f29cb2f8d57b`. The READ MORE link should redirect to the proposal page

fix(UI): fix READ MORE link in truncated proposal not working

---

package.json
src/helpers/utils.ts
src/queues/processors/proposalFactory.ts
src/queues/processors/scheduler.ts
test/integrations/utils.test.ts

All emails are sent to all users, regardless of their subscription preferences
Fix #80 
Users should only receive email types they have subscribed to
- Add filter before sending each email type, to send it to only emails subscribed to the given email type
- Currently hard to test, only way know is to console.log ` await getVerifiedSubscriptions('summary');` somewhere in your code (and change the args to other email type), and see that it returns the correct database row. Requires your test DB to be populated with some test data.
More robusts tests will come later

fix: send email to only users subscribed to the given email type

---

src/templates/newProposal/html.hbs
src/templates/summary/index.ts
src/templates/utils.ts

A regex rule is incorrect, and causing issues by invalidating all html closing tags (`</`)
Fix the regex
- Fix the regex rule, by ignoring `</` when matching `/`
- Fix some grammar
- open `http://localhost:3006/preview/newProposal?id=0x9171495a9dea3c604784a3261168e615f85b727092fa185bc5ad2226567ac0e5`
- proposal body should be formatted correctly, without displaying closing html as plain text

fix: fix incorrect regex

---

src/helpers/utils.ts

the `/subscriber` endpoint is now returning the first found match, sorted by created DESC. When there is duplicate and last one is not verified, it will return the not verified one instead of the verified one.
When there is duplicated, prioritize the verified row first
- Change the query sort order, to return `verified` user in priority
- 2 rows with same address but different email in the DB
- Verify the oldest
- `/subscriber` should return the verified row, instead of the most recent unverified row

fix: find verified user first

---

src/helpers/utils.ts
src/rpc.ts
test/e2e/subscriber.test.ts
test/unit/helpers/utils.test.ts

We return an obfuscated version of the subscriber email
Stop returning it for privacy reason
- Stop returning the subscriber email
- Send ` curl -X POST localhost:3006/subscriber --header "Authenticate: 00" -H "Content-Type: application/json" -d '{"address": "0x91FD2c8d24767db4Ece7069AA27832ffaf8590f3"}'` with an wallet address existing in your test database.
- It should return a JSON object, with `status` and `subscriptions` keys, without `email`

fix: stop returning subscriber email

---

src/index.ts

We track user IP in the HTTP logs. Snapshot do not track user related data
Remove user IP from logs
- Remove user IP from http logs
- Run `yarn dev`
- Open some URL
- In the console, HTTP request should not contains the user IP

chore: remove IP from logs

---

.github/workflows/build-test.yml
jest.config.ts
package.json

- Disable test coverage for e2e tests
- Code coverage should be relative to the whole project, and not only from tested files
- Send test coverage report to codecov

chore: send test coverage report to codecov

---

src/queues/processors/proposalFactory.ts
test/unit/queues/processors/proposalFactory.test.ts

The current 10min delay between new proposal creation and email sending is too short, and deos not allow enough time for spam detection.
Bump the delay for up to 2hours.
In case the proposal voting period is < 2 hours, will delay by ¾ of the voting period.
Fix #157 
- Increase the new proposal email sending delay from 10min to 2h
- In case the voting period is < 2h, delay is voting period * 0.75
- Read the tests for the file
- Trust the test ?

fix: bump the new proposal delay to up to 2h

---

jest.config.ts
src/queues/processors/proposalFactory.ts
src/queues/utils.ts
test/unit/queues/utils.test.ts

Tests for proposalFactory were failing, due to dependencies to redis. The tested function by themselves does not depend on redis, and thus are failing for unrelated reasons (connection to redis from bull)
Extract the tested function in another utils.ts file
- Extract the `newProposalDelay()` into its own helper file, isolating it from any side effects from the queue system
- Ignore `dist` folder from test path
- Run `yarn test`
- The test should not fail anymore on the CI (was working fine on local)
Failing tests for queue system are due to the way Bull is connecting to redis on CI. Will be 
fixed by #67

fix: fix failing tests

---

src/helpers/sentry.ts

Sentry is always enabled, as long as DSN is set, and may send errors when developing on local.
- Enable sentry logger only on production
- Add a condition to enable sentry only on prod, by checking `NODE_ENV`
- `NODE_ENV` have been set to `production` on the prod server
- N/A

chore: enable sentry only on production

---

src/templates/closedProposal/html.hbs
src/templates/closedProposal/text.hbs
src/templates/newProposal/html.hbs
src/templates/newProposal/text.hbs
src/templates/styles/proposal-activity.scss

As requested by @less, to have some kind of context about the email purpose, add a new introduction text explaining the purpose of the email
Fix #158 
- Add new introduction text to new/closed proposal emails
- Observe the change in the email previewer
- `http://localhost:3006/preview/newProposal?id=0x88583c43b196ec86cee45345611b582108f1d6933ab688a7cae992a6baa552a6`
- `http://localhost:3006/preview/closedProposal?id=0x88583c43b196ec86cee45345611b582108f1d6933ab688a7cae992a6baa552a6`

feat: add introduction text to email

---

src/templates/closedProposal/text.hbs
src/templates/index.ts
src/templates/newProposal/text.hbs

Some characters in space title are escaped
Disable characters escaping on space name
Fix #181 
- Disable characters escaping on space name
- Visit https://snapshot.org/#/daodungeon.eth/proposal/0x101a17d7d07c789778bb6342518f38700e9226bd9bdf7b7376416bb61eaccd38
- Space name should not be escape anymore

fix: fix escaped characters

---

src/helpers/snapshot.ts
src/queues/processors/proposalFactory.ts
src/templates/closedProposal/index.ts
src/templates/newProposal/index.ts
src/templates/summary/index.ts
test/fixtures/proposals.ts

Emails are filtering out only flagged proposal/spaces, and may include low quality content from non-verified spaces.
Filtering out proposals from non-verified spaces
Fix #196 
- Add a filter to only process proposals from verified spaces
- Go to `http://localhost:3006/preview/newProposal?id=0x77ceed96fe9868b0f6df55fa88b96d9bf32494f78f990ebd6bf32bdaab40e7a6`
- It should return an error, since the given proposal ID is from a non-verified space
- Try passing an ID from a verified space, it should succeed 
- Join a few non-verified space with your account
- Go to http://localhost:3006/preview/summary?id=[YOUR-ETH-ADDRESS]
- It should only shows proposals from verified spaces

fix: filter out proposals from non-verified spaces

---

package.json
src/helpers/metrics.ts
src/index.ts
yarn.lock

- The metrics lib is logging every http requests. This is creating a log of noises, as a webserver is getting a lot of invalid requests, spam, bot, etc..., and the http request metrics  is reporting a lot of unrelated data.
- Theres' a few repetition among repository for the metrics logic setup.
- The metrics for the http requests should only include routes defined in the express app
- Migrate the bootstrapping and metrics setup to snapshot-metrics
- add a whitelist of routes to be tracked by the metrics system
- normalize path, so `/send/1` and `/send/2` are tracked as a single `/send/ID`
- Use snapshot-metrics to handle metrics setup
- Rename `queued_mailing_jobs` metrics to `mailing_queued_jobs_count` to follow naming convention
- Go to `http://localhost:3006/subscriptionsList`
- Go to …

fix: use snapshot-metrics

---

src/templates/summary/index.ts

We pass a list of spaces to the `getProposals` query, fetching all proposals for the summary email. 
The issue is that when that list is empty, `getProposals` will return all spaces, instead of nothing. 
Should return early by returning an empty array when there's no activities from the verified spaces followed by the user.
- return an empty array as soon as possible
before fix: 
- Go to `http://localhost:3000/preview/summary`
- It should show a summary with only unverified spaces
after fix:
- Go to `http://localhost:3000/preview/summary` 
- Should show nothing

fix: fix summary returning all spaces when there's no verified spaces

---

src/templates/closedProposal/index.ts
src/templates/newProposal/index.ts
src/templates/summary/index.ts
src/templates/utils.ts
test/unit/templates/utils.test.ts

Following this conversation https://discord.com/channels/955773041898573854/1090359266763874384/1148911823853207553 and fix #239 
This PR add a `?app=envelop` query params to all proposal links

fix: add tracker to proposal link

---

src/templates/utils.ts
test/unit/templates/utils.test.ts

`new URL` making things complicated to just add `app` param
How to test:
- open your console
- Run
```js
function linkWithTracker(link) {
const _link = new URL(link);
_link.searchParams.set('app', 'envelop');
return _link.toString();
}
linkWithTracker("https://snapshot.org/#/stgdao.eth/proposal/0x82586192cf58f438cfee7101afde68df11ab3be071a6f7c05d1a3e8506836ee2")
// https://snapshot.org/?app=envelop#/stgdao.eth/proposal/0x82586192cf58f438cfee7101afde68df11ab3be071a6f7c05d1a3e8506836ee2
```

fix: search params are added in middle of URL

---

src/helpers/mail.ts

On mail send error, the error object is logged as `[Array]` without details.
This PR improve the error logging, by logging the error object properly

chore: log more error details to sentry

---

src/helpers/snapshot.ts

Fix for new format introduced in https://github.com/snapshot-labs/snapshot-hub/pull/836

fix: fix graphql query to follow new hub format

---

src/helpers/utils.ts

Fix missing parenthesis in SQL query, making it return more results than expected

fix: fix missing parenthesis in where query

---

src/helpers/snapshot.ts

Add support for passing `apiKey` to `HUB_URL` .env var

feat: add support for api key when connecting to snapshot hub

---

src/helpers/schema.sql

We have a few SQL using the `verified > 0` where filter.
Adding an index on this column will speed up the query
Run the following query on prod db 
```sql
ALTER TABLE subscribers ADD INDEX verified (`verified`);
```

feat: add an index to the `verified` column in the database
