snapshot-labs/envelop

- package.json
Restart node on hbs and json file changes
> chore: watch more file extensions

- src/helpers/snapshot.ts
- src/templates/summary/index.hbs
Grouping all proposals by space
> feat: summary email should be grouped by space

- src/helpers/snapshot.ts
in reference to https://github.com/snapshot-labs/envelop/pull/16#discussion_r1133223717
Only truncate the body when needed
> fix: truncate body only when necessary

- src/preview/index.ts
- src/rpc.ts
- src/sender.ts
- src/templates/index.ts
DRY template preview code, use the same template builder introduced in #10
> refactor: refactor template previewer to use the new templates builder

- .github/workflows/build-test.yml
- jest.config.ts
- package.json
- src/helpers/snapshot.ts
- test/fixtures/proposals.ts
- test/unit/helpers/snapshot.test.ts
- yarn.lock
Add tests for `helpers/snapshot.ts`
The current test is mainly testing that the output is correctly formatted (grouped by status and space, shortBody and votes properties setting, etc ...).
It's testing the features added in the previous PR
> chore: add tests

- LICENSE
> chore: fix missing LICENSE

- src/rpc.ts
- src/templates/builder.ts
- src/templates/partials/layout.html.hbs
- src/templates/partials/layout.text.hbs
- src/templates/utils.ts
- test/e2e/update.test.ts
- test/unit/templates/index.test.ts
Reverts snapshot-labs/envelop#95
> Revert "feat: separate update and unsubscribe link in footer"

- src/templates/summary/index.ts
Merging of #115 into `main` has gone wrong, with duplicating the code instead of merging it.
This PR remove duplicate code
> fix: fix invalid merge

- README.md
Add test coverage badge to README
> chore: add test badge to README

- src/templates/newProposal/html.hbs
Current label is a little long too small screen
Rename it to `Author`, as suggested by @bonustrack 
- Rename `Submitted by` to `Author`
> fix: rename "Submitted by" to "Author"

- src/templates/index.ts
Fix encoding issue in email subject
> fix: fix encoding issue in subject

- src/helpers/metrics.ts
Fix invalid SQL query for fetching non-verified users
> fix: fix invalid sql query for unverified user

- src/helpers/metrics.ts
- src/queues/index.ts
Track the number of sent emails, per type, in the metrics
> feat: track sent emails count by type

- src/queues/utils.ts
- src/templates/styles/styles.scss
fix #216 
Fix missing style for blockquote element
> fix(UI): add missing style for blockquote

- package.json
- src/rpc.ts
- yarn.lock
- Fix wrong sentry capture context signature
> chore: fix wrong sentry contexts key

- package.json
- src/helpers/metrics.ts
- yarn.lock
Upgrade package to enable db connections instrumentation
> fix: upgrade snapshot-metrics

- README.md
- jest.config.ts
- package.json
- test/e2e/subscribe.test.ts
- test/e2e/subscriber.test.ts
- test/e2e/unsubscribe.test.ts
- test/e2e/update.test.ts
- test/e2e/verify.test.ts
- test/setup.ts
- test/setupDb.ts
- test/teardown.ts
Add yarn task `yarn test:setup` to setup the test database
> chore: add test setup task

- src/templates/newProposal/html.hbs
Fix #255 
Fixing typo in link to proposal's author
> fix: typo fix in proposal's author link

- src/templates/closedProposal/html.hbs
- src/templates/newProposal/html.hbs
- src/templates/utils.ts
- test/unit/templates/utils.test.ts
Fix #254 
Fix issue where the tracker link (?app=envelop) was inserted multiple time.
> fix: fix tracker link inserted multiple times

- src/helpers/mail.ts
Log less data when mail sending is successful, only log important stuff
> chore: log less output on success
